name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: |
#        docker build . --file Dockerfile --tag andreiboghean/course_configurator:$(date +%s)
#        docker image push andreiboghean/course_configurator:$(date +%s)


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          file: ./Dockerfile
          push: true
